### ISSUE TITLE
Cannot set up speeddial entries for local urls - edit: Or ANY urls

### ISSUE THREAD

**Issue by westy** [jariz/tabbie#118]
Hi,

Am trying to set up a speeddial entry to our local Jira server, http://jira, but Tabbie does not seem to let 
me use this. It says the url is invalid.
Is it validating the URL for a valid extension, such as .com or .net, say?
 
I’d want to set up others for sites I’m working with on localhost too, but they do not work either.

Hopefully this is a simple fix, and one you can understand a requirement for!

Cheers

**Comment by westy** [comment]
Oh, it won't let me use other URLs either, e.g. https://repos.mycompanyname.co.uk/hgweb.cgi

**Comment by westy** [comment]
Or https://www.sencha.com/forum/

So, basically, speeddial does not work at all...

**Comment by erenhatirnaz** [comment]
Thank you for reporting the issue. That feature was added by me. This is my fault. I will try to fix this issue.

**Comment by erenhatirnaz** [comment]
I tried this cases now, but didn't give me an error. That feature was added by me. I used this regular expression to validation: `((((ht|f)tp(s?))\:\/\/){1}\S+)` ([source](https://github.com/jariz/tabbie/blob/master/src/columns/speeddial/speed-dial-dialog.html#L229)) . Your links are valid for this regex. https://regex101.com/r/KqHV64/1 . Can you share the screenshot in the Chrome console?

**Comment by westy** [comment]
Here you go.
I've tried at home as well as at work, and get the same thing, for ANY url.

It means the speeddial is unusable, in its current form.

![tabbie capture](https://cloud.githubusercontent.com/assets/657393/19597434/757aaa2c-978c-11e6-8ba8-8b8ddcfda734.PNG)

**Comment by erenhatirnaz** [comment]
My friend have tried and get the same error like your. He updated the chrome and fixed this issue. Too interesting. I don't know why. Can you try update Chrome?

**Comment by westy** [comment]
Oh, it's updating now... I thought it did that automatically.

**Comment by westy** [comment]
Yeah, that works now.

Thanks!

**Comment by westy** [comment]
Just got home, my extensions synced, and have the same issue here:
[image: Inline images 1]

It seems to be ALL urls, not just local ones.

**Comment by jariz** [comment]
@westy that image didn't work, try posting it again on the github site (without using email replying)

**Comment by westy** [comment]
@jariz Yeah. I don't think it was that different from the one above.

It's fine now, after I forced an update of Chrome, so will close the issue.


It may be an idea to not validate the URL though, in my opinion, since could then have entries to other protocols or even inline javascript - crazy perhaps, but the user should be in charge :)
