### ISSUE TITLE
Uncertain how to use Tabbie

### ISSUE THREAD

**Issue by hallshouse** [jariz/tabbie#123]
After installing Tabbie 1.1.3 in Chrome v56.0.2924.87 (64-bit) on Windows10, if I want to use Tabbie, I left click the Tabbie icon in the toobar and get the menu with the first item being "Tabbie - Material New Tab Page", this menu then has options (greyed out), then the remove, hide and manage Chrome extensions menu items.
When I click on the Tabbie - Material New Tab Page item it opens the Chrome Extensions > Tabbie already installed panel.

I understand what this extension does, but am not sure how to actually use/configure it.
How do you use this extension?

**Comment by jariz** [comment]
`cmd+t` 😄    
The icon does nothing but was made required by google for all extensions a year ago (no one still understands why this is the case...)

**Comment by hallshouse** [comment]
So, fine, if the icon does nothing, again...
How do we actually use the plugin?

**Comment by jariz** [comment]
Like I said, you open a new tab.
I'm sorry, but it literally says 'new tab page' in the extension name, not sure how we can make that more clear.
The icon is only there because google forces us to.

**Comment by hallshouse** [comment]
The only "New tab page" it opens is the "Chrome Extensions > Tabbie already installed panel."
After you open this, what can an end user do?

**Comment by jariz** [comment]
I really don't understand. It opens the chrome store when you open a new tab?

**Comment by hallshouse** [comment]
When I click on the "Tabbie - Material New Tab Page" menu item form your icon, it opens this page. After this I cannot do anything else with your extension.

This issue may be because I have no idea what to do as there are no instructions to take me further, or it may be broken, but I cannot tell you because there are no instructions and no other options to choose from.

Can you do one thing?
Can you tell us:
How do we: Tabbie keeps you informed, inspired, and up to date through it's beautiful and customizable columns.
How do we: Tabbie replaces your 'new tab' page with your favorite websites.
How do we: Choose exactly what content you want to see.

I have tried every method of (from a end user perspective) trying to find how to add anything to Tabbie and have no idea how to do this.

I'm sure your product works and would be really great with some simple instructions of how to use it.

**Comment by jariz** [comment]
It's a new tab page extension. It replaces your new tab page. If you open a new tab, it will show and then tell you exactly what you can do with it. The UI of the icon is bad, I agree, but I've explained multiple times now why that icon does what it does.

Despite maybe letting the button open tabbie, I really don't see what else we can do to improve it.
I don't see this is an issue.

**Comment by hallshouse** [comment]
Bingo! That was all I needed to know!

In chrome, it's rare that I open tabs manually so I had never thought of using the extension this way.
Thanks for the simple instruction. your extension is a great resource that will change the way i use Chrome.

Best Regards,
