### ISSUE TITLE
Feature Request: Setting for automatic refreshes

### ISSUE THREAD

**Issue by navarr** [jariz/tabbie#16]
The ability to set an interval in which the columns automatically refresh if the tab is open would be wonderful.

I commonly find myself leaving the tab open as I open other tabs and then come back to it only to find stale data.

**Comment by jariz** [comment]
Good idea! However, there's no 'global preferences' screen, and I'm not planning on adding one.  
So I think I'm still gonna add this, but not as a changable setting, and just let the columns refresh every 10 minutes.  
Unless you have a better idea, of course.
