### ISSUE TITLE
Column Request: Feedly

### ISSUE THREAD

**Issue by navarr** [jariz/tabbie#17]
#7 is nice, but you know what would be really nice?  A column of whatever popular RSS reader you use.  Feedly is one of the better ones, so I make this column request.

**Comment by jariz** [comment]
It's gonna be either #7 or #17 then, I'm not sure right now which I'm gonna pick.  
They're too much work to do both.

**Comment by jariz** [comment]
Proud to say that it is now fixed and live. Click the + button when adding a column.

**Comment by rbhalla** [comment]
Am I missing a step here? How does one get their feedly feed as a column using this method?
