### ISSUE TITLE
[BUG] Latest update of Tabbie seems to have broken the font size

### ISSUE THREAD

**Issue by ktkization** [jariz/tabbie#32]
The column font is to large in the colums

![screenshot](https://cloud.githubusercontent.com/assets/3750869/6770855/c0295e4a-d0de-11e4-94ac-7b51899771c2.png)

**Comment by jariz** [comment]
Friend of mine also notified me of this, looking into it...

**Comment by ktkization** [comment]
cool

**Comment by jariz** [comment]
Live on chrome store now. Click 'update all extensions' in extensions overview

**Comment by ktkization** [comment]
Ok. Thanks

**Comment by ktkization** [comment]
works well now.
