### ISSUE TITLE
Getting the following errors on recent update

### ISSUE THREAD

**Issue by wayferer** [jariz/tabbie#34]
See attached.

![screen shot 2015-03-22 at 5 45 48 pm](https://cloud.githubusercontent.com/assets/1575559/6772137/5aedd074-d0bb-11e4-8d92-e484330132bb.png)

**Comment by jariz** [comment]
Weird blue links are from a corrupt update which has been fixed by now.
Click 'update all' in chrome extension overview.
Reddit error is #33 which I'll fix tomorrow.

**Comment by wayferer** [comment]
Thank you.
