### ISSUE TITLE
Vertical Scrolling with tiles outside of viewport

### ISSUE THREAD

**Issue by Limess** [jariz/tabbie#39]
I can add more tiles than fit onto a full width/height window, however I can't access these tiles aside from scrolling using a middle mouse button click-and-drag. They can't be accessed by scrollwheel, arrow keys or a scrollbar.

I'd expect to either not be able to add these additional tiles, or be able to access them via normal scrolling.

Additionally, when viewing "about", these additional tiles are visible below the about section.

**Comment by jariz** [comment]
This is addressed in #35, I'm planning on adding a scrollbar when the columns overflow. Good idea about the about dialog, I added that I need to make the dialog fixed in that ticket.
