### ISSUE TITLE
Request: App-Launcher/Shortcuts

### ISSUE THREAD

**Issue by 2ManyPixels** [jariz/tabbie#5]
Title says it all. I think this NTP looks incredibly promising but I think it needs a lot more tiles. Most importantly: Some way to launch apps and/or websites.

**Comment by Hutchy68** [comment]
Looks very promising but needs definitely needs an app launcher and website launcher. Ability to pick the content you want to see. eg GutHub, I want to choose the repos I want not daily, weekly, etc.

**Comment by jariz** [comment]
Fixed @ b405a684685090228082937f0fa5c28e4cf3d4e0. Not as a column though, but same idea.  
![](http://i.imgur.com/14uGgZD.png)

**Comment by 2ManyPixels** [comment]
Even better than a column - nicely done. Thx
