### ISSUE TITLE
" Add a new column - feedly " is not working.

### ISSUE THREAD

**Issue by ElRakabawi** [jariz/tabbie#70]
When i press the " plus " button to add a new customized column, nothing happens, I can't type for something to search, i can't do anything but looking to this.
![screenshot from 2015-06-03 06 48 57](https://cloud.githubusercontent.com/assets/5153654/7952334/d722b562-09bc-11e5-9c7d-4c73b25bfdc8.png)

**Comment by jariz** [comment]
You are the first to report this issue.  
Can you hit ctrl+shift+j after opening the search and copy & paste what you see?  
Also maybe try removing and installing the extension again.

**Comment by ElRakabawi** [comment]
I tried to re-install the extension several times, but nothing goes better.
This the screenshots after hiting " ctrl+shift+j " 
![screenshot from 2015-06-03 13 00 25](https://cloud.githubusercontent.com/assets/5153654/7957880/471e2e9c-09f3-11e5-8cea-c4344a10adde.png)
Console doesn't load anything when i press the " plus " button on the top-right corner, and stops loading anything after that, like a dead page.
I tried playing around, i found that also the history button is not working, giving an error in the console.
![screenshot from 2015-06-03 13 09 38](https://cloud.githubusercontent.com/assets/5153654/7957936/a6f0593a-09f3-11e5-9dc1-088500c1ccaf.png)
![screenshot from 2015-06-03 13 01 21](https://cloud.githubusercontent.com/assets/5153654/7957980/e61d59fa-09f3-11e5-8b02-e1c7210b2de2.png)

My enviroment:
```
elrakabawi@elrakabawi:~$ google-chrome --version
Google Chrome 36.0.1985.143 
elrakabawi@elrakabawi:~$ whereis google-chrome
google-chrome: /usr/bin/google-chrome /usr/bin/X11/google-chrome /usr/share/man/man1/google-chrome.1
elrakabawi@elrakabawi:~$ lsb_release -d
Description:	Ubuntu 14.04.1 LTS
```

**Comment by jariz** [comment]
The only thing I can conclude out of this is that the manifest (which has all permissions listed) appears to be the same as the previous version (which should be impossible) for you.
I've tested it on many platforms so far and haven't seen anything like this.
Perhaps completely resetting your chrome might help. Have you tried it on a another computer / VM?

**Comment by ElRakabawi** [comment]
As you guessed, it finely worked on my VirtualBox with windows 7 on it.
![screenshot from 2015-06-06 00 04 17](https://cloud.githubusercontent.com/assets/5153654/8015252/a4acfcee-0bdf-11e5-9159-b779b8beeaaf.png)

I shall try re-installing my current version of chrome, or to update it.
and i will keep you informed.

**Comment by jariz** [comment]
Ha! I was actually setting up a Ubuntu VM but didn't get to it yet.
Weird problem, but because I'm paranoid I'll still test it on Ubuntu in the
next few days.
