### ISSUE TITLE
Designer News link missing www. Hence all links to designernews.co returning website not available.

### ISSUE THREAD

**Issue by risonsimon** [jariz/tabbie#71]
Please change designernews.co to www.designernews.co for chrome app. None of the links to designernews are working. For example, ASK DN links are giving this error.

**Comment by jariz** [comment]
Oh wow, that's pretty stupid. Guess you shouldn't leave DNS up to designers.

**Comment by navarr** [comment]
Is this going to be pushed onto the Chrome store or do I have to start loading Tabbie unpacked?  It's still broken in my copy of Chrome.

**Comment by jariz** [comment]
Did you click 'update extensions now'?
Because  
![](http://i.imgur.com/g7wsRkkb.jpg)

**Comment by navarr** [comment]
Of course, @jariz.  Both my computer and the Chrome Web Store say that the most recent version is 1.0 - which was released before this fix.

**Comment by joshfarrant** [comment]
Still waiting for this to be pushed to the store - any updates @jariz
