### ISSUE TITLE
Tabbie is Slow

### ISSUE THREAD

**Issue by baazoo** [jariz/tabbie#88]
Why Tabbie is so slow? Chrome's native pages should be blazing fast. I gave up on iChrome (a similar concept) just because it was slow. It is fine to use it as a homepage though.

Is this a problem with Polymer pages or is it a bug?

**Comment by jariz** [comment]
This doesn't really help me at all. I've checked performance quite often, and took out most bottle necks in the application. Fact is that it just has a lot of data to load and render, even if it's a 'chrome native page'.  
If you can name any specific parts of the application that you think are problematic, I can have a look at it.
