### ISSUE TITLE
Resize columns

### ISSUE THREAD

**Issue by jariz** [jariz/tabbie#9]
When in edit mode, columns should be made resizable by dragging it's corners. Resizing in width will go in steps of 25% (with 25% being the minimum of course). Resizing in height will be in steps of 50%.

**Comment by jariz** [comment]
Fixed 79f5e3c0accdb9fbc3e7af30a32a32c18661acc4

**Comment by ktkization** [comment]
I thought it would be better if the columns could be resized to any width or height. This would enable a user to have a more flexible layout
