### ISSUE TITLE
Chrome - ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by vkeusebio** [jariz/tabbie#92]
I got this

```No webpage was found for the web address: chrome-extension://efgjigapegihcgalgmamadpfdebaihoa/tab.html```

I just followed the instructions, its a clean fork/clone of tabbie

**Comment by vkeusebio** [comment]
Its working now but I got a blank window.

![image](https://cloud.githubusercontent.com/assets/15170164/10896516/70a1bb28-816f-11e5-96db-bab70e16ec04.png)

**Comment by jariz** [comment]
Please follow the development environment installation instructions [here](https://github.com/jariz/tabbie/blob/master/CONTRIBUTING.md)

**Comment by vkeusebio** [comment]
Yes, I did. Same result.
