### ISSUE TITLE
some link always open a new tab- effectively destroying the purpose of a new tab page?

### ISSUE THREAD

**Issue by Gameboy24** [jariz/tabbie#94]
I love tabbie, however if this is meant to be new chrome://newtab page, then it should never open links in a new tab. I end up having 2 or more tabbie pages open at a time because every time I make a new tab, and  click the title of a column it makes a new tab instead of continuing. 

Same thing with the app column, should just continue on the current tab just like chrome://apps

**Comment by jariz** [comment]
Sorry for my super late reply, but this was done because most people preferred it this way (including me), optionally we could add a setting or something, but you could create a separate issue for that.
