### ISSUE TITLE
Codepen padding issue

### ISSUE THREAD

**Issue by angrybakon** [jariz/tabbie#95]
The codepen tab is missing the right padding.

Also, it could be best if items had a thin border around them. That would make it look more consistent when we have white background (which is frequent) in some codepen.

![screen shot 2016-01-06 at 14 45 42](https://cloud.githubusercontent.com/assets/5608624/12143889/598abc44-b484-11e5-92d3-b92b79e967b4.png)

**Comment by jariz** [comment]
Codepen needs to be removed from tabbie itself. It's ugly and pointless and there's a 'Codepen Editor Picks' column that can be found by searching which even looks better.

**Comment by angrybakon** [comment]
> there's a 'Codepen Editor Picks' column that can be found by searching

What do you mean by that?

**Comment by jariz** [comment]
When you click the '+' button when adding a new column, you can enter
codepen and also add a codepen column through there which looks better than
the build in one does right now.

**Comment by angrybakon** [comment]
Oh, I see. I have never noticed this button. Thanks :)
